name: ROS 2 CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          rosdistro: [rolling]
          os: [ubuntu-18.04] # ,ubuntu-20.04, macOS-latest, windows-latest]
          include:
          - rosdistro: rolling
            repos_branch: master
    runs-on: ${{ matrix.os }}
    steps:
    - if: runner.os == 'Windows'
      uses: actions/cache@v1
      with:
        path: ${{env.TEMP}}/chocolatey
        key: ${{matrix.os}}-chocolatey-${{github.job_id}}
        restore-keys: ${{matrix.os}}-chocolatey-
    - if: runner.os == 'Linux'
      # azure ubuntu repo can be flaky so add an alternate source
      run: sed -e 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' -e t -e d /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/nonazure.list
    - if: runner.os == 'Linux'
      run: |
        echo ::set-env name=CFLAGS::$CFLAGS --coverage
        echo ::set-env name=CXXFLAGS::$CXXFLAGS --coverage
        echo ::set-env name=COLCON_CMAKE_ARGS::-DCMAKE_BUILD_TYPE=Debug
    - name: Acquire ROS dependencies
      uses: ros-tooling/setup-ros@master
    - name: Build and test ROS
      id: ros_ci
      uses: ros-tooling/action-ros-ci@master
      env:
        RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      with:
        package-name: >
          rmw_cyclonedds_cpp
          rmw_implementation
        target-ros2-distro: ${{matrix.rosdistro}}
        extra-cmake-args: ${{env.COLCON_CMAKE_ARGS}}
        colcon-mixin-name: coverage-gcc
        vcs-repo-file-url: >
          https://raw.githubusercontent.com/ros2/ros2/${{ matrix.repos_branch }}/ros2.repos
          https://raw.githubusercontent.com/${{github.repository}}/${{github.sha}}/.github/resources/suppress_other_rmw.repos
        coverage-ignore-pattern: i-should-not-need-this-argument
    - if: runner.os == 'Linux'
      name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ${{ steps.ros_ci.outputs.ros-workspace-directory-name }}/lcov/total_coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - if: runner.os == 'Linux'
      uses: codecov/codecov-action@v1.0.10
      with:
        file: ${{ steps.ros_ci.outputs.ros-workspace-directory-name }}/lcov/total_coverage.info
        fail_ci_if_error: false
    - run: find ${{ steps.ros_ci.outputs.ros-workspace-directory-name }}
    - name: Upload debug stuff
      uses: actions/upload-artifact@v2
      with:
        name: debugstuff
        path: |
          ${{ steps.ros_ci.outputs.ros-workspace-directory-name }}/lcov
          ${{ steps.ros_ci.outputs.ros-workspace-directory-name }}/log
          **/*.info
          **/*.coverage
          **/*.gcno
          **/*.gcda
          **/CMakeCache.txt
      if: always()  # upload the logs even when the build fails
